name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
          args: "pylint src/vcs/"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get -y install appstream appstream-util desktop-file-utils gettext

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build

      - name: Meson test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
